### ISSUE TITLE
get dev dependencies from setup.cfg

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/wipac-dev-mypy-action#1]
As mentioned in https://github.com/WIPACrepo/keycloak-rest-services/pull/52, there are other ways to list requirements than in `requirements-dev.txt`, and we should install them if possible.

For example:
```
pip install -e .[tests]
```

or
```
pip install -e .[dev]
```

**Comment by ric-evans** [comment]
this is solved by https://github.com/WIPACrepo/wipac-dev-mypy-action/pull/2 + https://github.com/WIPACrepo/wipac-dev-py-setup-action/pull/22
